/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;
import Controlador.ConexionMYSQL;
import Controlador.Funciones;
import Modelo.Medicamentos;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Fantasma-Enginner
 */
public class Frm_Medicamentos extends javax.swing.JFrame {

    /**
     * Creates new form Frm_Medicamentos
     */
    
     public static ConexionMYSQL CN = new ConexionMYSQL();
    public Funciones FUN = new Funciones();
    public static Medicamentos ME = new Medicamentos();
        
    
    public static String cod_d, cod_m, id;
    public static int swd;
    public Frm_Medicamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Txt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Txt_ppo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_desc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_pres = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_lab = new javax.swing.JTextField();
        Btn_nuevo = new javax.swing.JButton();
        Btn_Guardar = new javax.swing.JButton();
        Btn_actualizar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        Btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Medicamentos");
        setType(java.awt.Window.Type.POPUP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        jLabel1.setText("Código Medicamento:");

        jLabel2.setText("Principio Activo:");

        Txt_ppo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_ppoActionPerformed(evt);
            }
        });

        jLabel3.setText("Descripción:");

        Txt_desc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_descActionPerformed(evt);
            }
        });

        jLabel4.setText("Presentación:");

        jLabel5.setText("Laboratorio:");

        Btn_nuevo.setText("Nuevo");
        Btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_nuevoActionPerformed(evt);
            }
        });

        Btn_Guardar.setText("Guardar");
        Btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_GuardarActionPerformed(evt);
            }
        });

        Btn_actualizar.setText("Actualizar");
        Btn_actualizar.setEnabled(false);
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.setEnabled(false);
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Txt_codigo)
                    .addComponent(Txt_ppo)
                    .addComponent(Txt_pres, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Txt_desc))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Txt_lab)))
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(Btn_buscar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(Btn_nuevo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_actualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_eliminar)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_buscar))
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_ppo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_desc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Txt_pres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Txt_lab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_nuevo)
                    .addComponent(Btn_Guardar)
                    .addComponent(Btn_actualizar)
                    .addComponent(Btn_eliminar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_ppoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_ppoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_ppoActionPerformed

    private void Txt_descActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_descActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_descActionPerformed

    private void Btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_nuevoActionPerformed
        // TODO add your handling code here:
        Limpiar();
    }//GEN-LAST:event_Btn_nuevoActionPerformed

    private void Btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_GuardarActionPerformed
        // TODO add your handling code here:
         if (Txt_codigo.getText().trim().isEmpty() || Txt_ppo.getText().trim().isEmpty() || Txt_desc.getText().trim().isEmpty() || Txt_pres.getText().trim().isEmpty()|| Txt_lab.getText().trim().isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Existen campos vacíos por favor verifique.");
        } else {
            Save();
        }
    }//GEN-LAST:event_Btn_GuardarActionPerformed

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
        // TODO add your handling code here:
         Update();
    }//GEN-LAST:event_Btn_actualizarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
        // TODO add your handling code here:
        int confirmar = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar este registro?", "CONFIRMAR", 0);
        if (confirmar == 0) {
            Delete();
        }
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
        // TODO add your handling code here:
         new Frm_Filtro_Med().setVisible(true);
    }//GEN-LAST:event_Btn_buscarActionPerformed
 private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        Limpiar();
    }                                 

    private void Txt_codigoTyped(java.awt.event.KeyEvent evt) {                                 
        FUN.CantidadDigitos(evt, Txt_codigo, 10);
    }                                

    private void Txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {                                   
        FUN.PasarTextAText(evt, Txt_codigo, Txt_ppo, "Este campo es requerido");
    }                                  

    private void Txt_ppoKeyTyped(java.awt.event.KeyEvent evt) {                                    
        FUN.CantidadDigitos(evt, Txt_ppo, 50);
    }                                   

    private void Txt_ppoKeyPressed(java.awt.event.KeyEvent evt) {                                      
        FUN.PasarTextAText(evt, Txt_ppo, Txt_desc, "Este campo es requerido");
    }                                     

    private void Txt_descKeyTyped(java.awt.event.KeyEvent evt) {                                       
        FUN.CantidadDigitos(evt, Txt_desc, 50);
    }                                      

    private void Txt_descKeyPressed(java.awt.event.KeyEvent evt) {                                         
        FUN.PasarTextAText(evt, Txt_desc, Txt_pres, "Este campo es requerido");
    }                                        

    private void Txt_presKeyTyped(java.awt.event.KeyEvent evt) {                                       
        FUN.CantidadDigitos(evt, Txt_pres, 50);
    }                                      

    private void Txt_presKeyPressed(java.awt.event.KeyEvent evt) {                                         
        FUN.PasarTextAText(evt, Txt_pres, Txt_lab, "Este campo es requerido");
    }                                        

    private void Txt_labKeyTyped(java.awt.event.KeyEvent evt) {                                   
        FUN.CantidadDigitos(evt, Txt_lab, 50);
    }                                  

    
    private void Txt_labKeyPressed(java.awt.event.KeyEvent evt) {
        
        FUN.PasarTextAButtun(evt, Txt_lab, Btn_Guardar, "Este campo es requerido");
    }                                    

    public void Save() {
        try {
            ME.Medicamentos(Integer.parseInt(Txt_codigo.getText()),
                        Txt_ppo.getText(),
                        Txt_desc.getText(),
                        Txt_pres.getText(),
                        Txt_lab.getText());
            ME.INSERT_MEDICAMENTOS(CN.getConnection());
            formWindowOpened(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void Update() {
        try {
            ME.Medicamentos(Integer.parseInt(Txt_codigo.getText()),
                        Txt_ppo.getText(),
                        Txt_desc.getText(),
                        Txt_pres.getText(),
                        Txt_lab.getText());
            ME.UPDATE_MEDICAMENTOS(CN.getConnection(), id);
            formWindowOpened(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void Delete(){
        try {
            ME.DELETE_MEDICAMENTOS(CN.getConnection(), id);
            formWindowOpened(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
    public void Limpiar(){
        swd = 1;
        FUN.LimpiarText(jPanel3);
        swd = 0;
    }                        

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_Medicamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_Medicamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Guardar;
    public static javax.swing.JButton Btn_actualizar;
    private javax.swing.JButton Btn_buscar;
    public static javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_nuevo;
    public static javax.swing.JTextField Txt_codigo;
    public static javax.swing.JTextField Txt_desc;
    public static javax.swing.JTextField Txt_lab;
    public static javax.swing.JTextField Txt_ppo;
    public static javax.swing.JTextField Txt_pres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
