/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ConexionMYSQL;
import Controlador.Funciones;
import Modelo.PROVEEDORES;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author Dario
 */
public class Frm_PROVEEDORES extends javax.swing.JFrame {
  public static ConexionMYSQL CN = new ConexionMYSQL();
    public Funciones FUN = new Funciones();
    public static PROVEEDORES PR = new PROVEEDORES();
    
     public static String cod_d, cod_m, id;
    public static int swd;
    /**
     * Creates new form Frm_PROVEEDORES
     */
    public Frm_PROVEEDORES() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Txt_codigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Txt_razonsocial = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Txt_direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Txt_contacto = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Txt_ciudad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Txt_telefono = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Txt_celular = new javax.swing.JTextField();
        Btn_nuevo = new javax.swing.JButton();
        Btn_guardar = new javax.swing.JButton();
        Btn_actualizar = new javax.swing.JButton();
        Btn_eliminar = new javax.swing.JButton();
        Btn_buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PROVEEDORES");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 77, Short.MAX_VALUE)
        );

        jLabel1.setText("Codigo de Proveedor");

        jLabel2.setText("Razon Social");

        Txt_razonsocial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_razonsocialActionPerformed(evt);
            }
        });

        jLabel3.setText("Direccion");

        jLabel4.setText("Contacto");

        Txt_contacto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txt_contactoActionPerformed(evt);
            }
        });

        jLabel5.setText("Ciudad");

        jLabel6.setText("Telefono");

        jLabel7.setText("Celular");

        Btn_nuevo.setText("Nuevo");
        Btn_nuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_nuevoActionPerformed(evt);
            }
        });

        Btn_guardar.setText("Guardar");
        Btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_guardarActionPerformed(evt);
            }
        });

        Btn_actualizar.setText("Actualizar");
        Btn_actualizar.setEnabled(false);
        Btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_actualizarActionPerformed(evt);
            }
        });

        Btn_eliminar.setText("Eliminar");
        Btn_eliminar.setEnabled(false);
        Btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_eliminarActionPerformed(evt);
            }
        });

        Btn_buscar.setText("Buscar");
        Btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Btn_nuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_guardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btn_eliminar))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Txt_codigo, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                            .addComponent(Txt_razonsocial)
                            .addComponent(Txt_contacto)
                            .addComponent(Txt_telefono))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(Txt_ciudad, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(Txt_celular)
                                    .addComponent(Txt_direccion, javax.swing.GroupLayout.Alignment.LEADING)))
                            .addComponent(Btn_buscar))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn_buscar))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Txt_razonsocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(Txt_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(Txt_contacto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Txt_ciudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Txt_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(Txt_celular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn_nuevo)
                    .addComponent(Btn_guardar)
                    .addComponent(Btn_actualizar)
                    .addComponent(Btn_eliminar))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Txt_razonsocialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_razonsocialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_razonsocialActionPerformed

    private void Txt_contactoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txt_contactoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txt_contactoActionPerformed

    private void Btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_guardarActionPerformed
if (Txt_codigo.getText().trim().isEmpty() || Txt_razonsocial.getText().trim().isEmpty() || Txt_direccion.getText().trim().isEmpty() || Txt_contacto.getText().trim().isEmpty()|| Txt_ciudad.getText().trim().isEmpty()|| Txt_telefono.getText().trim().isEmpty()|| Txt_celular.getText().trim().isEmpty()  ) {
            JOptionPane.showMessageDialog(null, "Existen campos vacíos por favor verifique.");
        } else {
            Save();
        } 

// TODO add your handling code here:
    }//GEN-LAST:event_Btn_guardarActionPerformed

    private void Btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_actualizarActionPerformed
 Update();        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_actualizarActionPerformed

    private void Btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_eliminarActionPerformed
    int confirmar = JOptionPane.showConfirmDialog(null, "Esta seguro que desea eliminar este registro?", "CONFIRMAR", 0);
        if (confirmar == 0) {
            Delete();
        }// TODO add your handling code here:
    }//GEN-LAST:event_Btn_eliminarActionPerformed

    private void Btn_nuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_nuevoActionPerformed
     Limpiar();        // TODO add your handling code here:
    }//GEN-LAST:event_Btn_nuevoActionPerformed

    private void Btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_buscarActionPerformed
       new Frm_Filtro_Prov().setVisible(true);
       // TODO add your handling code here:
    }//GEN-LAST:event_Btn_buscarActionPerformed
  private void formWindowOpened(java.awt.event.WindowEvent evt) {                                  
        Limpiar();
  }
   private void Txt_codigoTyped(java.awt.event.KeyEvent evt) {                                 
        FUN.CantidadDigitos(evt, Txt_codigo, 10);
    }                                

    private void Txt_codigoKeyPressed(java.awt.event.KeyEvent evt) {                                   
        FUN.PasarTextAText(evt, Txt_codigo, Txt_razonsocial, "Este campo es requerido");
    }                                  

    private void Txt_razonsocialKeyTyped(java.awt.event.KeyEvent evt) {                                    
        FUN.CantidadDigitos(evt, Txt_razonsocial, 50);
    }                                   

    private void Txt_razonsocialKeyPressed(java.awt.event.KeyEvent evt) {                                      
        FUN.PasarTextAText(evt, Txt_razonsocial, Txt_direccion, "Este campo es requerido");
    }                                     

    private void Txt_direccionKeyTyped(java.awt.event.KeyEvent evt) {                                       
        FUN.CantidadDigitos(evt, Txt_direccion, 50);
    }                                      

    private void Txt_direccionKeyPressed(java.awt.event.KeyEvent evt) {                                         
        FUN.PasarTextAText(evt, Txt_direccion, Txt_contacto, "Este campo es requerido");
    }                                        

    private void Txt_contactoKeyTyped(java.awt.event.KeyEvent evt) {                                       
        FUN.CantidadDigitos(evt, Txt_contacto, 50);
    }                                      

    private void Txt_contactoKeyPressed(java.awt.event.KeyEvent evt) {                                         
        FUN.PasarTextAText(evt, Txt_contacto, Txt_ciudad, "Este campo es requerido");
    }                                        

    private void Txt_ciudadKeyTyped(java.awt.event.KeyEvent evt) {                                   
        FUN.CantidadDigitos(evt, Txt_ciudad, 50);
    }                                  
     private void Txt_ciudadKeyPressed(java.awt.event.KeyEvent evt) {                                         
        FUN.PasarTextAText(evt, Txt_ciudad, Txt_telefono, "Este campo es requerido");
     }
      private void Txt_telefonoKeyTyped(java.awt.event.KeyEvent evt) {                                   
        FUN.CantidadDigitos(evt, Txt_telefono, 50);
    }                                  
     private void Txt_telefonoKeyPressed(java.awt.event.KeyEvent evt) {                                         
        FUN.PasarTextAText(evt, Txt_telefono, Txt_celular, "Este campo es requerido");
     }
      private void Txt_celularKeyTyped(java.awt.event.KeyEvent evt) {                                   
        FUN.CantidadDigitos(evt, Txt_celular, 50);
      }
    
    private void Txt_celularKeyPressed(java.awt.event.KeyEvent evt) {
        
        FUN.PasarTextAButtun(evt, Txt_celular, Btn_guardar, "Este campo es requerido");
    }
    public void Save() {
        try {
            PR.PROVEEDORES(Integer.parseInt(Txt_codigo.getText()),
                         Txt_razonsocial.getText(),
                        Txt_direccion.getText(),
                        Txt_contacto.getText(),
                        Txt_ciudad.getText(),
                        Txt_telefono.getText(),
                        Txt_celular.getText());
            PR.INSERT_PROVEEDORES(CN.getConnection());
            formWindowOpened(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void Update() {
        try {
            PR.PROVEEDORES(Integer.parseInt(Txt_codigo.getText()),
                        Txt_razonsocial.getText(),
                        Txt_direccion.getText(),
                        Txt_contacto.getText(),
                        Txt_ciudad.getText(),
                        Txt_telefono.getText(),
                        Txt_celular.getText());
            PR.UPDATE_PROVEEDORES(CN.getConnection(), id);
            formWindowOpened(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
    
    public void Delete(){
        try {
            PR.DELETE_PROVEEDORES(CN.getConnection(), id);
            formWindowOpened(null);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        
    }
    
    public void Limpiar(){
        swd = 1;
        FUN.LimpiarText(jPanel2);
        swd = 0;
    }                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_PROVEEDORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_PROVEEDORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_PROVEEDORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_PROVEEDORES.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frm_PROVEEDORES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Btn_actualizar;
    public static javax.swing.JButton Btn_buscar;
    public static javax.swing.JButton Btn_eliminar;
    private javax.swing.JButton Btn_guardar;
    private javax.swing.JButton Btn_nuevo;
    public static javax.swing.JTextField Txt_celular;
    public static javax.swing.JTextField Txt_ciudad;
    public static javax.swing.JTextField Txt_codigo;
    public static javax.swing.JTextField Txt_contacto;
    public static javax.swing.JTextField Txt_direccion;
    public static javax.swing.JTextField Txt_razonsocial;
    public static javax.swing.JTextField Txt_telefono;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
